export const CultureIndexAbi = [
  {
    inputs: [{ internalType: "address", name: "_manager", type: "address" }],
    stateMutability: "payable",
    type: "constructor",
  },
  { inputs: [], name: "ADDRESS_ZERO", type: "error" },
  { inputs: [], name: "ALREADY_DROPPED", type: "error" },
  { inputs: [], name: "ALREADY_VOTED", type: "error" },
  { inputs: [], name: "ARRAY_LENGTH_MISMATCH", type: "error" },
  {
    inputs: [{ internalType: "address", name: "target", type: "address" }],
    name: "AddressEmptyCode",
    type: "error",
  },
  { inputs: [], name: "CULTURE_INDEX_EMPTY", type: "error" },
  { inputs: [], name: "DOES_NOT_MEET_QUORUM", type: "error" },
  { inputs: [], name: "FailedInnerCall", type: "error" },
  { inputs: [], name: "INVALID_ANIMATION_URL", type: "error" },
  { inputs: [], name: "INVALID_BPS_SUM", type: "error" },
  { inputs: [], name: "INVALID_CREATOR_BPS", type: "error" },
  { inputs: [], name: "INVALID_DESCRIPTION", type: "error" },
  { inputs: [], name: "INVALID_ERC20_VOTING_WEIGHT", type: "error" },
  { inputs: [], name: "INVALID_ERC721_VOTING_WEIGHT", type: "error" },
  { inputs: [], name: "INVALID_IMAGE", type: "error" },
  { inputs: [], name: "INVALID_MEDIA_TYPE", type: "error" },
  { inputs: [], name: "INVALID_NAME", type: "error" },
  { inputs: [], name: "INVALID_PIECE_ID", type: "error" },
  { inputs: [], name: "INVALID_QUORUM_BPS", type: "error" },
  { inputs: [], name: "INVALID_SIGNATURE", type: "error" },
  { inputs: [], name: "INVALID_SUBSTRING", type: "error" },
  { inputs: [], name: "INVALID_TEXT", type: "error" },
  {
    inputs: [{ internalType: "address", name: "impl", type: "address" }],
    name: "INVALID_UPGRADE",
    type: "error",
  },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "MAX_NUM_CREATORS_EXCEEDED", type: "error" },
  { inputs: [], name: "NOT_DROPPER_ADMIN", type: "error" },
  { inputs: [], name: "NOT_MANAGER", type: "error" },
  { inputs: [], name: "NotInitializing", type: "error" },
  { inputs: [], name: "ONLY_CALL", type: "error" },
  { inputs: [], name: "ONLY_DELEGATECALL", type: "error" },
  { inputs: [], name: "ONLY_PROXY", type: "error" },
  { inputs: [], name: "ONLY_UUPS", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "SIGNATURE_EXPIRED", type: "error" },
  { inputs: [], name: "UNSUPPORTED_UUID", type: "error" },
  { inputs: [], name: "WEIGHT_TOO_LOW", type: "error" },
  { anonymous: false, inputs: [], name: "EIP712DomainChanged", type: "event" },
  {
    anonymous: false,
    inputs: [],
    name: "ERC721VotingTokenLocked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract ERC721CheckpointableUpgradeable",
        name: "ERC721VotingToken",
        type: "address",
      },
    ],
    name: "ERC721VotingTokenUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldMinVotingPowerToCreate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newMinVotingPowerToCreate",
        type: "uint256",
      },
    ],
    name: "MinVotingPowerToCreateSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldMinVotingPowerToVote",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newMinVotingPowerToVote",
        type: "uint256",
      },
    ],
    name: "MinVotingPowerToVoteSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "pieceId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sponsor",
        type: "address",
      },
      {
        components: [
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          {
            internalType: "enum ICultureIndex.MediaType",
            name: "mediaType",
            type: "uint8",
          },
          { internalType: "string", name: "image", type: "string" },
          { internalType: "string", name: "text", type: "string" },
          { internalType: "string", name: "animationUrl", type: "string" },
        ],
        indexed: false,
        internalType: "struct ICultureIndex.ArtPieceMetadata",
        name: "metadata",
        type: "tuple",
      },
      {
        components: [
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "uint256", name: "bps", type: "uint256" },
        ],
        indexed: false,
        internalType: "struct ICultureIndex.CreatorBps[]",
        name: "creators",
        type: "tuple[]",
      },
    ],
    name: "PieceCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "pieceId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "remover",
        type: "address",
      },
    ],
    name: "PieceDropped",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldQuorumVotesBPS",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newQuorumVotesBPS",
        type: "uint256",
      },
    ],
    name: "QuorumVotesBPSSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "impl",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "pieceId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "voter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "weight",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalWeight",
        type: "uint256",
      },
    ],
    name: "VoteCast",
    type: "event",
  },
  {
    inputs: [],
    name: "MAX_NUM_CREATORS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_QUORUM_VOTES_BPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PIECE_DATA_MAXIMUMS",
    outputs: [
      { internalType: "uint256", name: "name", type: "uint256" },
      { internalType: "uint256", name: "description", type: "uint256" },
      { internalType: "uint256", name: "image", type: "uint256" },
      { internalType: "uint256", name: "text", type: "uint256" },
      { internalType: "uint256", name: "animationUrl", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "VOTE_TYPEHASH",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "_currentPieceId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newMinVotingPowerToCreate",
        type: "uint256",
      },
    ],
    name: "_setMinVotingPowerToCreate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newMinVotingPowerToVote",
        type: "uint256",
      },
    ],
    name: "_setMinVotingPowerToVote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "newQuorumVotesBPS", type: "uint256" },
    ],
    name: "_setQuorumVotesBPS",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address[]", name: "from", type: "address[]" },
      { internalType: "uint256[][]", name: "pieceIds", type: "uint256[][]" },
      { internalType: "uint256[]", name: "deadline", type: "uint256[]" },
      { internalType: "uint8[]", name: "v", type: "uint8[]" },
      { internalType: "bytes32[]", name: "r", type: "bytes32[]" },
      { internalType: "bytes32[]", name: "s", type: "bytes32[]" },
    ],
    name: "batchVoteForManyWithSig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "checklist",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "contractVersion",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          {
            internalType: "enum ICultureIndex.MediaType",
            name: "mediaType",
            type: "uint8",
          },
          { internalType: "string", name: "image", type: "string" },
          { internalType: "string", name: "text", type: "string" },
          { internalType: "string", name: "animationUrl", type: "string" },
        ],
        internalType: "struct ICultureIndex.ArtPieceMetadata",
        name: "metadata",
        type: "tuple",
      },
      {
        components: [
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "uint256", name: "bps", type: "uint256" },
        ],
        internalType: "struct ICultureIndex.CreatorBps[]",
        name: "creatorArray",
        type: "tuple[]",
      },
    ],
    name: "createPiece",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "description",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "dropTopVotedPiece",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "pieceId", type: "uint256" },
          {
            components: [
              { internalType: "address", name: "creator", type: "address" },
              { internalType: "uint256", name: "bps", type: "uint256" },
            ],
            internalType: "struct ICultureIndex.CreatorBps[]",
            name: "creators",
            type: "tuple[]",
          },
          { internalType: "address", name: "sponsor", type: "address" },
        ],
        internalType: "struct ICultureIndex.ArtPieceCondensed",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "dropperAdmin",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { internalType: "bytes1", name: "fields", type: "bytes1" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "version", type: "string" },
      { internalType: "uint256", name: "chainId", type: "uint256" },
      { internalType: "address", name: "verifyingContract", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      { internalType: "uint256[]", name: "extensions", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "pieceId", type: "uint256" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "getAccountVotingPowerForPiece",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "pieceId", type: "uint256" }],
    name: "getPieceById",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "pieceId", type: "uint256" },
          {
            components: [
              { internalType: "string", name: "name", type: "string" },
              { internalType: "string", name: "description", type: "string" },
              {
                internalType: "enum ICultureIndex.MediaType",
                name: "mediaType",
                type: "uint8",
              },
              { internalType: "string", name: "image", type: "string" },
              { internalType: "string", name: "text", type: "string" },
              { internalType: "string", name: "animationUrl", type: "string" },
            ],
            internalType: "struct ICultureIndex.ArtPieceMetadata",
            name: "metadata",
            type: "tuple",
          },
          {
            components: [
              { internalType: "address", name: "creator", type: "address" },
              { internalType: "uint256", name: "bps", type: "uint256" },
            ],
            internalType: "struct ICultureIndex.CreatorBps[]",
            name: "creators",
            type: "tuple[]",
          },
          { internalType: "address", name: "sponsor", type: "address" },
          { internalType: "bool", name: "isDropped", type: "bool" },
          { internalType: "uint256", name: "creationBlock", type: "uint256" },
        ],
        internalType: "struct ICultureIndex.ArtPiece",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTopVotedPiece",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "pieceId", type: "uint256" },
          {
            components: [
              { internalType: "string", name: "name", type: "string" },
              { internalType: "string", name: "description", type: "string" },
              {
                internalType: "enum ICultureIndex.MediaType",
                name: "mediaType",
                type: "uint8",
              },
              { internalType: "string", name: "image", type: "string" },
              { internalType: "string", name: "text", type: "string" },
              { internalType: "string", name: "animationUrl", type: "string" },
            ],
            internalType: "struct ICultureIndex.ArtPieceMetadata",
            name: "metadata",
            type: "tuple",
          },
          {
            components: [
              { internalType: "address", name: "creator", type: "address" },
              { internalType: "uint256", name: "bps", type: "uint256" },
            ],
            internalType: "struct ICultureIndex.CreatorBps[]",
            name: "creators",
            type: "tuple[]",
          },
          { internalType: "address", name: "sponsor", type: "address" },
          { internalType: "bool", name: "isDropped", type: "bool" },
          { internalType: "uint256", name: "creationBlock", type: "uint256" },
        ],
        internalType: "struct ICultureIndex.ArtPiece",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "pieceId", type: "uint256" },
      { internalType: "address", name: "voter", type: "address" },
    ],
    name: "getVote",
    outputs: [
      {
        components: [
          { internalType: "address", name: "voterAddress", type: "address" },
          { internalType: "uint256", name: "weight", type: "uint256" },
        ],
        internalType: "struct ICultureIndex.Vote",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "pieceId", type: "uint256" },
      { internalType: "address", name: "voter", type: "address" },
    ],
    name: "hasVoted",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_votingPower", type: "address" },
      { internalType: "address", name: "_initialOwner", type: "address" },
      { internalType: "address", name: "_maxHeap", type: "address" },
      { internalType: "address", name: "_dropperAdmin", type: "address" },
      {
        components: [
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "string", name: "checklist", type: "string" },
          { internalType: "string", name: "template", type: "string" },
          { internalType: "uint256", name: "tokenVoteWeight", type: "uint256" },
          {
            internalType: "uint256",
            name: "pointsVoteWeight",
            type: "uint256",
          },
          { internalType: "uint256", name: "quorumVotesBPS", type: "uint256" },
          {
            internalType: "uint256",
            name: "minVotingPowerToVote",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minVotingPowerToCreate",
            type: "uint256",
          },
          {
            components: [
              { internalType: "uint256", name: "name", type: "uint256" },
              { internalType: "uint256", name: "description", type: "uint256" },
              { internalType: "uint256", name: "image", type: "uint256" },
              { internalType: "uint256", name: "text", type: "uint256" },
              {
                internalType: "uint256",
                name: "animationUrl",
                type: "uint256",
              },
            ],
            internalType: "struct ICultureIndex.PieceMaximums",
            name: "pieceMaximums",
            type: "tuple",
          },
          {
            internalType: "enum ICultureIndex.MediaType",
            name: "requiredMediaType",
            type: "uint8",
          },
          {
            internalType: "enum ICultureIndex.RequiredMediaPrefix",
            name: "requiredMediaPrefix",
            type: "uint8",
          },
        ],
        internalType: "struct IRevolutionBuilder.CultureIndexParams",
        name: "_cultureIndexParams",
        type: "tuple",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "maxAnimationUrlLength",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxDescriptionLength",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxHeap",
    outputs: [{ internalType: "contract MaxHeap", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxImageLength",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxNameLength",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxTextLength",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minVotingPowerToCreate",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minVotingPowerToVote",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "nonces",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingOwner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pieceCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "pieces",
    outputs: [
      { internalType: "uint256", name: "pieceId", type: "uint256" },
      {
        components: [
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          {
            internalType: "enum ICultureIndex.MediaType",
            name: "mediaType",
            type: "uint8",
          },
          { internalType: "string", name: "image", type: "string" },
          { internalType: "string", name: "text", type: "string" },
          { internalType: "string", name: "animationUrl", type: "string" },
        ],
        internalType: "struct ICultureIndex.ArtPieceMetadata",
        name: "metadata",
        type: "tuple",
      },
      { internalType: "address", name: "sponsor", type: "address" },
      { internalType: "bool", name: "isDropped", type: "bool" },
      { internalType: "uint256", name: "creationBlock", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pointsVoteWeight",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proxiableUUID",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "quorumVotes",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "quorumVotesBPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "pieceId", type: "uint256" }],
    name: "quorumVotesForPiece",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "requiredMediaPrefix",
    outputs: [
      {
        internalType: "enum ICultureIndex.RequiredMediaPrefix",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "requiredMediaType",
    outputs: [
      { internalType: "enum ICultureIndex.MediaType", name: "", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "template",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenVoteWeight",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "topVotedPieceId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "topVotedPieceMeetsQuorum",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "totalVoteWeights",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_newImpl", type: "address" }],
    name: "upgradeTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_newImpl", type: "address" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "pieceId", type: "uint256" }],
    name: "vote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "pieceIds", type: "uint256[]" },
    ],
    name: "voteForMany",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "uint256[]", name: "pieceIds", type: "uint256[]" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint8", name: "v", type: "uint8" },
      { internalType: "bytes32", name: "r", type: "bytes32" },
      { internalType: "bytes32", name: "s", type: "bytes32" },
    ],
    name: "voteForManyWithSig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "votes",
    outputs: [
      { internalType: "address", name: "voterAddress", type: "address" },
      { internalType: "uint256", name: "weight", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "votingPower",
    outputs: [
      {
        internalType: "contract IRevolutionVotingPower",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
